-- AlterEnum
ALTER TYPE "ExerciseGoal" ADD VALUE IF NOT EXISTS 'NECK_MOBILITY';
ALTER TYPE "ExerciseGoal" ADD VALUE IF NOT EXISTS 'NECK_STRENGTH';
ALTER TYPE "ExerciseGoal" ADD VALUE IF NOT EXISTS 'CALF_MOBILITY';
ALTER TYPE "ExerciseGoal" ADD VALUE IF NOT EXISTS 'WRIST_MOBILITY';

-- AlterEnum
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'NECK';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'CALVES';
ALTER TYPE "BodyPart" ADD VALUE IF NOT EXISTS 'FOREARMS';
